# Multi-stage build.

#Stage 1 builder 
FROM python:3.11 AS builder

WORKDIR /app

COPY app/requirements.txt .
RUN pip install --prefix=/install -r requirements.txt

#Stage 2 final
FROM python:3.11-slim

WORKDIR /app
COPY --from=builder /install /usr/local
COPY app/app.py .
COPY app/model.joblib .

EXPOSE 8000

CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000"]
